// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1cLXC5mDeSeO9JOZcy1aXoQ6JbKlPfxY',
    appId: '1:945357131533:web:c7d68177b5aa40c0e16a44',
    messagingSenderId: '945357131533',
    projectId: 'chat-app-b9365',
    authDomain: 'chat-app-b9365.firebaseapp.com',
    storageBucket: 'chat-app-b9365.appspot.com',
    measurementId: 'G-C6TYX3NH8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-AFmOugTYL3fWGZY3Zq4EEMfOnODCRWo',
    appId: '1:945357131533:android:ed670f41d6d10448e16a44',
    messagingSenderId: '945357131533',
    projectId: 'chat-app-b9365',
    storageBucket: 'chat-app-b9365.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtjhKPItlzdPia2jfe5Ne6AAD7HZYis70',
    appId: '1:945357131533:ios:e34f83531fc59da2e16a44',
    messagingSenderId: '945357131533',
    projectId: 'chat-app-b9365',
    storageBucket: 'chat-app-b9365.appspot.com',
    iosClientId: '945357131533-ff81n4rrn1rp9mnt5t2u6ce683tdiuut.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtjhKPItlzdPia2jfe5Ne6AAD7HZYis70',
    appId: '1:945357131533:ios:0c28fdc8f4db2c67e16a44',
    messagingSenderId: '945357131533',
    projectId: 'chat-app-b9365',
    storageBucket: 'chat-app-b9365.appspot.com',
    iosClientId: '945357131533-ps9rs2snh53nuefpuirtla8qbem26pj7.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
